/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-21 06:54:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.queen;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminPotentialTiperList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/queen/../queen/adminNavbar.jsp", Long.valueOf(1684594758000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1683079470908L));
    _jspx_dependants.put("jar:file:/C:/swork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/honeytiper/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>꿀TIPer 관리자 - TIPer 승급 관리</title>\r\n");
      out.write("<style>\r\n");
      out.write("#searchNav{-webkit-justify-content: flex-end; justify-content: flex-end; }\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#h3_title{\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("	font-size: 26px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul{\r\n");
      out.write("	margin : 0 auto;\r\n");
      out.write("	border-right: 0;\r\n");
      out.write("	padding-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul li {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	float:left;\r\n");
      out.write("	list-style : none;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul li a{\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	color: black;\r\n");
      out.write("	padding : 9px 12px;\r\n");
      out.write("	border-right: solid 1px #ccc;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	text-decoration-line: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul li.on{\r\n");
      out.write("	background: #FFD400;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul li.on a{\r\n");
      out.write("	color:#fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#container003{\r\n");
      out.write("	margin: 0 auto;	\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	margin-top: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#sel1{\r\n");
      out.write("	height: 38px !important;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin-bottom: 0px;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sel2{\r\n");
      out.write("	height: 38px !important;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#sel3{\r\n");
      out.write("	height: 38px !important;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#table003{\r\n");
      out.write("	width: 95vw;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top_bar{\r\n");
      out.write("	display:flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdCenter_wrapper{\r\n");
      out.write(" 	display: flex;\r\n");
      out.write(" 	flex-wrap : wrap;\r\n");
      out.write(" 	justify-content: space-around;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdCenter_name_date{\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdCenter_name_id{\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdCenter{\r\n");
      out.write("	display: inline;\r\n");
      out.write(" 	margin: 10px 5px;;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdCenter_wrapper #name003{\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdCenter_wrapper #cate003{\r\n");
      out.write("	display: inline;\r\n");
      out.write(" 	margin: 20px 30px;\r\n");
      out.write(" 	vertical-align: middle;\r\n");
      out.write(" 	padding-top: 26px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdCenter_cate003_img_name{\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdCenter_wrapper #cate003 span{\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdCenter_name_id #name003{\r\n");
      out.write("	margin: 10px 0px;\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdCenter_name_id #id003{\r\n");
      out.write("	margin: 10px 0px;\r\n");
      out.write("	font-weight: lighter;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdCenter img{\r\n");
      out.write("	height: 100px;\r\n");
      out.write("	width: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btn_wrapper{\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btn_wrapper button{\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	background-color: #ffdf48;\r\n");
      out.write("	color: #5c3b0c;\r\n");
      out.write("	border-style: none;\r\n");
      out.write("	font-size:0.9rem;\r\n");
      out.write("	\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btn_wrapper .button_box_reject{\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	background-color: #E9E9E9;\r\n");
      out.write("	color: #5c3b0c;\r\n");
      out.write("	border-style: none;\r\n");
      out.write("	font-size:0.9rem;\r\n");
      out.write("	\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#paging_wrapper{\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pagingul {\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pagingul li {\r\n");
      out.write("  margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pagingul li a {\r\n");
      out.write("  display: block;\r\n");
      out.write("  padding: 5px 10px;\r\n");
      out.write("  border: 1px solid #ddd;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  color: #333;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pagingul li.on a {\r\n");
      out.write("  background-color: #FFD400;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 768px) {		/*=======================================================*/\r\n");
      out.write("\r\n");
      out.write("#table003{\r\n");
      out.write("	width: 65vw;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdCenter_wrapper #cate003{\r\n");
      out.write(" 	margin: 20px 5px;\r\n");
      out.write(" 	text-align: center;\r\n");
      out.write("    width: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top_bar{\r\n");
      out.write("	display:flex;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top_bar h3{\r\n");
      out.write("	width: 25%;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search_wrapper{\r\n");
      out.write("	width: 75%;\r\n");
      out.write("	display:flex;\r\n");
      out.write("	justify-content: flex-end;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	align-items: flex-end;\r\n");
      out.write("	margin-bottom: 3px;\r\n");
      out.write("}\r\n");
      out.write("#search_wrapper select{\r\n");
      out.write("	width: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search_wrapper input{\r\n");
      out.write("	width: 40%;\r\n");
      out.write("	margin-right: 5px !important;\r\n");
      out.write("}\r\n");
      out.write("#search_wrapper button{\r\n");
      out.write("	    width: 60px;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write(".form-control #sel2{\r\n");
      out.write("	margin-right:5px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"  src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/front/test.css\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/front/test.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"jumbotron\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!-- <title>Insert title here</title> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("*{\r\n");
      out.write("	font-family: none;\r\n");
      out.write("}\r\n");
      out.write(".menu-bar {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  left: -190px;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  width: 230px;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  background-color: #333;\r\n");
      out.write("  overflow: auto;\r\n");
      out.write("  transition: left 0.3s ease-in-out; \r\n");
      out.write("}\r\n");
      out.write(".menu-bar a {\r\n");
      out.write("  display: block;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-decoration: none !important;\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  transition: 0.3s;\r\n");
      out.write("  padding: 5px; \r\n");
      out.write("  margin:20px;\r\n");
      out.write("  font-size:16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar a:hover {\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("  background-color: #555;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write(".menu-bar .p{\r\n");
      out.write("color: #ffd400;\r\n");
      out.write("font-size: 15px;\r\n");
      out.write(" margin:20px;\r\n");
      out.write("}\r\n");
      out.write(".menu-bar .h3{\r\n");
      out.write("color: #ffd400;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sub-menu {\r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write(".menu-bar.active {\r\n");
      out.write("  left: 0;\r\n");
      out.write("}\r\n");
      out.write(".menu-icon {\r\n");
      out.write("  display: block;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  right: 10px;\r\n");
      out.write("  transform: translateY(-50%);\r\n");
      out.write("}\r\n");
      out.write(".menu-icon i {\r\n");
      out.write("  font-size: 36px;\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"menu-bar\">\r\n");
      out.write("<a href=\"index\" style=\"margin:0px 20px;\"><img onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/front/default.png'\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/front/LOGOy.png\" style=\"width:140px; hight: auto;\" title=\"꿀팁홈페이지로가기\"></a>\r\n");
      out.write("<p class=\"p\"style=\"margin-bottom:40px;\">관리자님 반갑습니다</p>\r\n");
      out.write("<h3 class=\"h3\"><a style=\"font-size:18.72px; font-weight:bold;\" href=\"goChart\">메인으로가기</a></h3>\r\n");
      out.write("  <a href=\"listuser\">회원리스트</a>\r\n");
      out.write("  <a href=\"listlesson\">강의리스트</a>\r\n");
      out.write("  <a href=\"getReportList\">블랙리스트관리</a>\r\n");
      out.write("  <a href=\"getPotentialTiperList\">승급요청처리</a>\r\n");
      out.write("  <a href=\"adminNoticeList\">공지사항 관리</a>\r\n");
      out.write("  <a href=\"adminFaqList\">F A Q 관리</a>\r\n");
      out.write("  <a href=\"callEscrowList\">에스크로내역</a>\r\n");
      out.write("  <a href=\"getDisputeResolutionList\">강의완료 및 취소</a>\r\n");
      out.write("  <a href=\"adminChkBtn\">관리자정보수정</a>\r\n");
      out.write("  <a class=\"p\" href=\"logOut\"style=\"font-weight:bold;font-size:18px;\">관리자 로그아웃</a>\r\n");
      out.write("<div class=\"menu-icon\">\r\n");
      out.write("    <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write(" const menuBar = document.querySelector('.menu-bar');\r\n");
      out.write(" const subMenus = document.querySelectorAll('.sub-menu');\r\n");
      out.write(" const menuIcon = document.querySelector('.menu-icon');\r\n");
      out.write("\r\n");
      out.write(" menuBar.addEventListener('mouseover', () => {\r\n");
      out.write("   menuBar.classList.add('active');\r\n");
      out.write("   subMenus.forEach(subMenu => subMenu.style.display = 'block');\r\n");
      out.write("   menuIcon.style.display = 'none';\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write(" menuBar.addEventListener('mouseout', () => {\r\n");
      out.write("   menuBar.classList.remove('active');\r\n");
      out.write("   subMenus.forEach(subMenu => subMenu.style.display = 'none');\r\n");
      out.write("   if (!menuBar.classList.contains('active')) {\r\n");
      out.write("     menuIcon.style.display = 'block';\r\n");
      out.write("   }\r\n");
      out.write(" });\r\n");
      out.write("</script> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<nav id=\"searchNav\" class=\"navbar navbar-expand-sm navbar-dark\">\r\n");
      out.write(" \r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"container003\">\r\n");
      out.write("  <div id=\"table003\">\r\n");
      out.write("	<div id=\"top_bar\">\r\n");
      out.write("		<h3 id=\"h3_title\">승급 관리</h3>\r\n");
      out.write("  		<div id=\"search_wrapper\">\r\n");
      out.write("  			<select class=\"search002\" id=\"sel1\" name=\"user_condition\" style=\"display:inline-block!important;margin-right:10px;\">\r\n");
      out.write("				<option value=\"user_id\">아이디</option>\r\n");
      out.write("				<option value=\"user_name\">이름</option>\r\n");
      out.write("    		</select>\r\n");
      out.write("    		<input class=\"search002\" type=\"text\" name=\"user_search\" id=\"sel2\" placeholder=\"검색어를 입력하세요.\">\r\n");
      out.write("    		<button class=\"btn btn-success\" type=\"submit\" class=\"search002\" id=\"sel3\">검색</button>\r\n");
      out.write("		</div>\r\n");
      out.write("    </div>\r\n");
      out.write("<hr id=\"br0203\">\r\n");
      out.write("\r\n");
      out.write("    <div id=\"table_wrapper\">\r\n");
      out.write("    <div id=\"data_table_body\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("  </div>\r\n");
      out.write("    \r\n");
      out.write("  <div id=\"paging_wrapper\">\r\n");
      out.write("  <ul id=\"pagingul\">\r\n");
      out.write("	</ul>\r\n");
      out.write("  </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <div id=\"footer\">\r\n");
      out.write("<!--   	<button type=\"button\" id=\"conWrite\" class=\"btn btn-primary\">글쓰기</button> -->\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var totalData; //총 데이터 수\r\n");
      out.write("var dataPerPage=5; //한 페이지에 나타낼 글 수\r\n");
      out.write("var pageCount = 5; //한 번에 나타낼 페이지 수 ([이전] 1 2 3 4 5 [다음])\r\n");
      out.write("var globalCurrentPage= 1; //현재 페이지\r\n");
      out.write("var dataList; //데이터 리스트\r\n");
      out.write(" \r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("\r\n");
      out.write("     //totalData(총 데이터 수) 구하기\r\n");
      out.write("	 dataList = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${TiperListJSON}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";		\r\n");
      out.write("     \r\n");
      out.write("     //totalData(총 데이터 수) 구하기\r\n");
      out.write("	 totalData = dataList.length;\r\n");
      out.write("     \r\n");
      out.write("     displayData(1, dataPerPage);\r\n");
      out.write("     paging(totalData, dataPerPage, pageCount, 1);\r\n");
      out.write("});\r\n");
      out.write(" \r\n");
      out.write("//현재 페이지(currentPage)와 페이지당 글 개수(dataPerPage) 반영\r\n");
      out.write("function displayData(currentPage, dataPerPage) {\r\n");
      out.write("\r\n");
      out.write("  let chartHtml = \"\";\r\n");
      out.write("\r\n");
      out.write("//Number로 변환하지 않으면 아래에서 +를 할 경우 스트링 결합이 되어버림.. \r\n");
      out.write("  currentPage = Number(currentPage);\r\n");
      out.write("  dataPerPage = Number(dataPerPage);\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" if (totalData < (currentPage - 1) * dataPerPage + dataPerPage){\r\n");
      out.write("	\r\n");
      out.write("	  for (\r\n");
      out.write("		var i = (currentPage - 1) * dataPerPage;\r\n");
      out.write("		    i < totalData;\r\n");
      out.write("			     i++\r\n");
      out.write("			   ) {\r\n");
      out.write("		  chartHtml +=\r\n");
      out.write("			  '<div class=\"tdCenter_wrapper\"><div class=\"tdCenter_cate003_img_name\"><div class=\"tdCenter\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/front/profile/'+dataList[i].tiper_img+'\" alt=\"예체능카테고리\"></div>'+\r\n");
      out.write("			 '<div class=\"tdCenter_name_date\"><div class=\"tdCenter_name_id\"><div class=\"tdCenter\" id=\"name003\">'+dataList[i].user_name+'</div>'+\r\n");
      out.write("			  '<div class=\"tdCenter\" id=\"id003\">@'+dataList[i].user_id+'</div></div>'+\r\n");
      out.write("			  '<div class=\"tdCenter\" id=\"date003\">'+dataList[i].tiper_date+'</div></div></div>'+\r\n");
      out.write("			  '<div class=\"tdCenter\" id=\"cate003\"><span>'+dataList[i].tiper_cate1+'</span></div>'+\r\n");
      out.write("			  '<div class=\"tdCenter\">'+\r\n");
      out.write("			  '<div id=\"btn_wrapper\"><button class=\"button_box\" onclick=\"location.href='+'\\'/updateTiperAgree?user_id='+dataList[i].user_id+'\\'\">승인</button>'+\r\n");
      out.write("			  '<button class=\"button_box_reject\" onclick=\"location.href='+'\\'/updateTiperReject?user_id='+dataList[i].user_id+'\\'\">거절</button></div>'+\r\n");
      out.write("			  '</div></div><br><hr>'\r\n");
      out.write("			   \r\n");
      out.write("\r\n");
      out.write("			   } \r\n");
      out.write(" }else{ \r\n");
      out.write("  \r\n");
      out.write("  for (\r\n");
      out.write("    var i = (currentPage - 1) * dataPerPage;\r\n");
      out.write("    i < (currentPage - 1) * dataPerPage + dataPerPage;\r\n");
      out.write("    i++\r\n");
      out.write("  ) {\r\n");
      out.write("	  chartHtml +=\r\n");
      out.write("		  '<div class=\"tdCenter_wrapper\"><div class=\"tdCenter_cate003_img_name\"><div class=\"tdCenter\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/front/profile/'+dataList[i].tiper_img+'\" alt=\"예체능카테고리\"></div>'+\r\n");
      out.write("		 '<div class=\"tdCenter_name_date\"><div class=\"tdCenter_name_id\"><div class=\"tdCenter\" id=\"name003\">'+dataList[i].user_name+'</div>'+\r\n");
      out.write("		  '<div class=\"tdCenter\" id=\"id003\">@'+dataList[i].user_id+'</div></div>'+\r\n");
      out.write("		  '<div class=\"tdCenter\" id=\"date003\">'+dataList[i].tiper_date+'</div></div></div>'+\r\n");
      out.write("		  '<div class=\"tdCenter\" id=\"cate003\"><span>'+dataList[i].tiper_cate1+'</span></div>'+\r\n");
      out.write("		  '<div class=\"tdCenter\">'+\r\n");
      out.write("		  '<div id=\"btn_wrapper\"><button class=\"button_box\" onclick=\"location.href='+'\\'/updateTiperAgree?user_id='+dataList[i].user_id+'\\'\">승인</button>'+\r\n");
      out.write("		  '<button class=\"button_box_reject\" onclick=\"location.href='+'\\'/updateTiperReject?user_id='+dataList[i].user_id+'\\'\">거절</button></div>'+\r\n");
      out.write("		  '</div></div><br><hr>'\r\n");
      out.write("  } //dataList는 임의의 데이터임.. 각 소스에 맞게 변수를 넣어주면 됨...\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write(" if( typeof chartHtml == \"undefined\" || chartHtml == ''){ chartHtml +=\" <id='if_undefined'><span>대기중인 회원이 없습니다.<span></div>\"}\r\n");
      out.write("$(\"#data_table_body\").html(chartHtml);\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("function paging(totalData, dataPerPage, pageCount, currentPage) {\r\n");
      out.write("\r\n");
      out.write("	  totalPage = Math.ceil(totalData / dataPerPage); //총 페이지 수\r\n");
      out.write("	  \r\n");
      out.write("	  if(totalPage<pageCount){\r\n");
      out.write("	    pageCount=totalPage;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  let pageGroup = Math.ceil(currentPage / pageCount); // 페이지 그룹\r\n");
      out.write("	  let endPage = pageGroup * pageCount; //화면에 보여질 마지막 페이지 번호\r\n");
      out.write("	  \r\n");
      out.write("	  if (endPage > totalPage) {\r\n");
      out.write("	    endPage = totalPage;\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("	  let startPage = endPage - (pageCount - 1); //화면에 보여질 첫번째 페이지 번호\r\n");
      out.write("	  let next = Number(currentPage)+1;\r\n");
      out.write("//	  let next = endPage +1;\r\n");
      out.write("	  let prev = Number(currentPage)-1;\r\n");
      out.write("//	  let prev = startPage - 1;\r\n");
      out.write("\r\n");
      out.write("	  let pageHtml = \"\";\r\n");
      out.write("\r\n");
      out.write("	  if (prev > 0) {\r\n");
      out.write("	    pageHtml += \"<li><a href='javascript:void(0)' id='prev'> 이전 </a></li>\";\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("	 //페이징 번호 표시 \r\n");
      out.write("	  for (var i = startPage; i <= endPage; i++) {\r\n");
      out.write("	    if (currentPage == i) {\r\n");
      out.write("	      pageHtml +=\r\n");
      out.write("	        '<li class=\"on\"><a href=\"javascript:void(0)\" id=\"' + i + '\">' + i + '</a></li>';\r\n");
      out.write("//	        '<li class=\"on\"><a href=\"javascript:displayData('+2+',5)\" id=\"' + i + '\">' + i + '</a></li>';\r\n");
      out.write("	    } else {\r\n");
      out.write("	      pageHtml += \"<li><a href='javascript:void(0)' id='\" + i + \"'>\" + i + \"</a></li>\";\r\n");
      out.write("	    }\r\n");
      out.write("	  }\r\n");
      out.write("	 \r\n");
      out.write("	 	console.log(\"토탈 : \"+ totalPage);\r\n");
      out.write("	 	console.log(\"엔드 : \"+ endPage);\r\n");
      out.write("	 	console.log(\"지금 : \"+ currentPage);\r\n");
      out.write("	 	console.log(\"다음 : \"+ next);\r\n");
      out.write("	 \r\n");
      out.write("	  if (next <= totalPage) {\r\n");
      out.write("	    pageHtml += '<li><a href=\"javascript:void(0);\" id=\"next\"> 다음 </a></li>';\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("	  $(\"#pagingul\").html(pageHtml);\r\n");
      out.write("//	  let displayCount = \"\";\r\n");
      out.write("//	  displayCount = \"현재 1 - \" + totalPage + \" 페이지 / \" + totalData + \"건\";\r\n");
      out.write("//	  $(\"#displayCount\").text(displayCount);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	  //페이징 번호 클릭 이벤트 \r\n");
      out.write("	  $(\"#pagingul li a\").click(function () {\r\n");
      out.write("	    let $id = $(this).attr(\"id\");\r\n");
      out.write("	    selectedPage = $(this).text();\r\n");
      out.write("\r\n");
      out.write("	    if ($id == \"next\") selectedPage = next;\r\n");
      out.write("	    if ($id == \"prev\") selectedPage = prev;\r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("	    //전역변수에 선택한 페이지 번호를 담는다...\r\n");
      out.write("	    globalCurrentPage = selectedPage;\r\n");
      out.write("	 \r\n");
      out.write("	    console.log(\"클릭시 글로벌 \"+globalCurrentPage);\r\n");
      out.write("	    \r\n");
      out.write("	    //글 목록 표시 재호출\r\n");
      out.write("	    displayData(globalCurrentPage, dataPerPage);\r\n");
      out.write("	    //페이징 표시 재호출\r\n");
      out.write("	    paging(totalData, dataPerPage, pageCount, globalCurrentPage);\r\n");
      out.write("	  });\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("$(\"#sel3\").click(function(){\r\n");
      out.write("	\r\n");
      out.write("	var search_condition=$('#sel1').val();\r\n");
      out.write("	var search_keyword=$('#sel2').val();\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({ // ajax로 데이터 가져오기\r\n");
      out.write("		method: \"POST\",\r\n");
      out.write("		url: \"searchPotentialTiperList\",\r\n");
      out.write("	 	data: {search_condition:search_condition, search_keyword:search_keyword},\r\n");
      out.write("		dataType: \"json\",\r\n");
      out.write("		async:false,\r\n");
      out.write("		success: function (data) {\r\n");
      out.write("//		 		alert(\"data: \" + JSON.stringify(data));\r\n");
      out.write("		   //totalData(총 데이터 수) 구하기\r\n");
      out.write("		   totalData = data.length;\r\n");
      out.write("	       //데이터 대입\r\n");
      out.write("	       dataList=data;\r\n");
      out.write("	       \r\n");
      out.write("	       if(typeof totalData == \"undefined\" || totalData == null || totalData == \"\"){ alert(\"검색결과가 없습니다.\");}\r\n");
      out.write("			 }\r\n");
      out.write("	 });		\r\n");
      out.write("	\r\n");
      out.write("	 //글 목록 표시 재호출\r\n");
      out.write("    displayData(1, 5);\r\n");
      out.write("    //페이징 표시 재호출\r\n");
      out.write("    paging(totalData, 5, pageCount, 1);\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
