/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-19 06:18:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.queen;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminUserList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/queen/../queen/adminNavbar.jsp", Long.valueOf(1684473104647L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1683079470908L));
    _jspx_dependants.put("jar:file:/C:/swork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/honeytiper/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원리스트</title>\r\n");
      out.write("<style>\r\n");
      out.write(".container {\r\n");
      out.write("	width: 65%;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("/* 나머지 요소들은 기본값인 z-index: 1로 설정 */\r\n");
      out.write("table {\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	border-bottom: 1px solid #ddd;\r\n");
      out.write("	padding: 5px 15px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	height: 38px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("	height: 21px;\r\n");
      out.write("	background: #f2f2f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#view-all-button, #search-button {\r\n");
      out.write("	border-style: none;\r\n");
      out.write("	background: #FFD400;\r\n");
      out.write("	color: #5c3b0c;\r\n");
      out.write("	margin: 5px;\r\n");
      out.write("	padding: 5px 18px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	font-size: 12pt;\r\n");
      out.write("	font-weight: bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sel3 {\r\n");
      out.write("	border-style: none;\r\n");
      out.write("	background: #FFD400;\r\n");
      out.write("	color: #5c3b0c;\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	font-size: 12pt;\r\n");
      out.write("	font-weight: bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#view-all-button:hover, #search-button:hover, #sel3:hover {\r\n");
      out.write("	background-color: #E6B800;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination-row {\r\n");
      out.write("	background-color: #e8f0fe;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination-row th {\r\n");
      out.write("	font-size: 12pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pagingul {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pagingul li {\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pagingul li a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	padding: 5px 10px;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pagingul li.on a {\r\n");
      out.write("	background-color: #FFD400;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#user-search {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	height: 17.5px; padding : 5px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search_wrapper {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	virtical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search_wrapper select {\r\n");
      out.write("	margin: 0 5px;\r\n");
      out.write("	height: 31.5px;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write(" var totalData; //총 데이터 수\r\n");
      out.write(" var dataPerPage = 10; //한 페이지에 나타낼 글 수\r\n");
      out.write(" var pageCount = 5; //페이징에 나타낼 페이지 수\r\n");
      out.write(" var globalCurrentPage= 1; //현재 페이지\r\n");
      out.write(" var dataList; //표시하려하는 데이터 리스트\r\n");
      out.write(" var search = $(\"#user-search\").val();\r\n");
      out.write(" var condition = $(\"#user-condition\").val();\r\n");
      out.write("\r\n");
      out.write("	function selTr(val){\r\n");
      out.write("	location.href=\"updateMoveUser?user_id=\"+val;\r\n");
      out.write("	}\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("	// 검색 버튼 클릭 이벤트\r\n");
      out.write("	function btnSFnc() {\r\n");
      out.write("	search = $(\"#user-search\").val();\r\n");
      out.write("	condition = $(\"#user-condition\").val();\r\n");
      out.write("	    ajaxFnc();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// 전체보기 버튼 클릭 이벤트\r\n");
      out.write("	function viewAllFnc() {\r\n");
      out.write("	    location.reload();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("//아약스 함수\r\n");
      out.write(" function ajaxFnc() {\r\n");
      out.write("     $.ajax({\r\n");
      out.write("         method: \"POST\",\r\n");
      out.write("         url: 'listuser',\r\n");
      out.write("         data:{\r\n");
      out.write("        	 'user_search' : search,\r\n");
      out.write("        	 'user_condition' : condition	 \r\n");
      out.write("         },\r\n");
      out.write("         success: function (res) {\r\n");
      out.write("         \r\n");
      out.write("             totalData = res.length;\r\n");
      out.write("             displayData(globalCurrentPage, dataPerPage, res);\r\n");
      out.write("             paging(totalData, dataPerPage, pageCount, globalCurrentPage);\r\n");
      out.write("         }\r\n");
      out.write("     });\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" $(document).ready(function () {\r\n");
      out.write("	 ajaxFnc();\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" function displayData(currentPage, dataPerPage, dataList) {\r\n");
      out.write("\r\n");
      out.write("	 let chartHtml = \"\";	\r\n");
      out.write("\r\n");
      out.write("	 currentPage = Number(currentPage);\r\n");
      out.write("	 dataPerPage = Number(dataPerPage);\r\n");
      out.write("	 let startPage = (currentPage - 1) * dataPerPage; //15\r\n");
      out.write("	 let endPage = (currentPage - 1) * dataPerPage + dataPerPage;\r\n");
      out.write("	 if(endPage > (dataList.length)) endPage = dataList.length;\r\n");
      out.write("\r\n");
      out.write("	 function formatDate(date) {\r\n");
      out.write("	     var d = new Date(date); \r\n");
      out.write("	     var month = '' + (d.getMonth() + 1);\r\n");
      out.write("	     var day = '' + d.getDate();\r\n");
      out.write("	     var year = d.getFullYear();\r\n");
      out.write("\r\n");
      out.write("	     if (month.length < 2) month = '0' + month;\r\n");
      out.write("	     if (day.length < 2) day = '0' + day;\r\n");
      out.write("\r\n");
      out.write("	     return [year, month, day].join('-');\r\n");
      out.write("	 }\r\n");
      out.write("\r\n");
      out.write("	 for (var i = startPage; i < endPage; i++) {\r\n");
      out.write("	 	\r\n");
      out.write("	     var formattedEscrowStart = formatDate(dataList[i].notice_start) || \"\";\r\n");
      out.write("	     var formattedEscrowEnd = formatDate(dataList[i].notice_end) || \"\";\r\n");
      out.write("     \r\n");
      out.write(" 	 chartHtml +=\r\n");
      out.write(" 	 \"<tr onclick=\\\"selTr(  \\'\"+dataList[i].user_id +\"\\'  )\\\" style='cursor: pointer'><td  style='text-overflow:ellipsis; overflow:hidden; white-space:nowrap;'>\"+ dataList[i].user_id +\r\n");
      out.write(" 	 \"</td><td  style='text-overflow:ellipsis; overflow:hidden; white-space:nowrap;'>\" + dataList[i].user_name +\r\n");
      out.write(" 	 \"</td><td style='text-overflow:ellipsis; overflow:hidden; white-space:nowrap;'>\" + (dataList[i].user_addr2 +  dataList[i].user_addr3 + dataList[i].user_addr4)+\r\n");
      out.write(" 	 \"</td><td  style='text-overflow:ellipsis; overflow:hidden; white-space:nowrap;'>\" + (dataList[i].user_tel || \"\")+\r\n");
      out.write(" 	 \"</td><td  style='text-overflow:ellipsis; overflow:hidden; white-space:nowrap;'>\" + (dataList[i].user_email || \"\")+\r\n");
      out.write(" 	 \"</td><td  style='text-overflow:ellipsis; overflow:hidden; white-space:nowrap;'>\" + (dataList[i].user_cate || \"\");\r\n");
      out.write(" 	 \r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write(" $(\"#dataTableBody\").html(chartHtml);\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" //페이징함수\r\n");
      out.write(" function paging(totalData, dataPerPage, pageCount, currentPage) {\r\n");
      out.write(" totalPage = Math.ceil(totalData / dataPerPage); //총 페이지 수\r\n");
      out.write("  \r\n");
      out.write(" if(totalPage<pageCount){\r\n");
      out.write("   pageCount=totalPage;\r\n");
      out.write(" }\r\n");
      out.write("  \r\n");
      out.write(" let pageGroup = Math.ceil(currentPage / pageCount); // 페이지 그룹\r\n");
      out.write(" let endPage = pageGroup * pageCount; //화면에 보여질 마지막 페이지 번호\r\n");
      out.write("\r\n");
      out.write(" if (endPage > totalPage) {\r\n");
      out.write("   endPage = totalPage;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" let startPage = endPage - (pageCount - 1); //화면에 보여질 첫번째 페이지 번호\r\n");
      out.write(" let next = Number(currentPage)+1;\r\n");
      out.write(" let prev = Number(currentPage)-1;\r\n");
      out.write("\r\n");
      out.write(" let pageHtml = \"\";\r\n");
      out.write("\r\n");
      out.write(" if (prev > 0) {\r\n");
      out.write("   pageHtml += \"<li><a href='javascript:void(0)' id='prev'> 이전 </a></li>\";\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" //페이징 번호 표시 \r\n");
      out.write(" for (var i = startPage; i <= endPage; i++) {\r\n");
      out.write(" 	if (currentPage == i) {\r\n");
      out.write(" 	  pageHtml +=\r\n");
      out.write(" 	    '<li class=\"on\"><a href=\"javascript:void(0)\" id=\"' + i + '\">' + i + '</a></li>';\r\n");
      out.write(" 	} else {\r\n");
      out.write(" 	  pageHtml += \"<li><a href='javascript:void(0)' id='\" + i + \"'>\" + i + \"</a></li>\";\r\n");
      out.write(" 	}\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" if (next <= totalPage) {\r\n");
      out.write("   pageHtml += '<li><a href=\"javascript:void(0);\" id=\"next\"> 다음 </a></li>';\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" $(\"#pagingul\").html(pageHtml);\r\n");
      out.write(" let displayCount = \"\";\r\n");
      out.write(" displayCount = \"현재 1 - \" + totalPage + \" 페이지 / \" + totalData + \"건\";\r\n");
      out.write(" $(\"#displayCount\").text(displayCount);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  //페이징 번호 클릭 이벤트 \r\n");
      out.write(" $(\"#pagingul li a\").click(function () {\r\n");
      out.write(" 	let $id = $(this).attr(\"id\");\r\n");
      out.write(" 	selectedPage = $(this).text();\r\n");
      out.write(" 	\r\n");
      out.write(" 	if ($id == \"next\") selectedPage = next;\r\n");
      out.write(" 	if ($id == \"prev\") selectedPage = prev;\r\n");
      out.write(" 	\r\n");
      out.write(" 	\r\n");
      out.write(" 	//전역변수에 선택한 페이지 번호를 담는다...\r\n");
      out.write(" 	globalCurrentPage = selectedPage;\r\n");
      out.write(" 	ajaxFnc();\r\n");
      out.write(" });\r\n");
      out.write("   \r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("*{\r\n");
      out.write("	font-family: none;\r\n");
      out.write("}\r\n");
      out.write(".menu-bar {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  left: -190px;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  width: 230px;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  background-color: #333;\r\n");
      out.write("  overflow: auto;\r\n");
      out.write("  transition: left 0.3s ease-in-out; \r\n");
      out.write("}\r\n");
      out.write(".menu-bar a {\r\n");
      out.write("  display: block;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-decoration: none !important;\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  transition: 0.3s;\r\n");
      out.write("  padding: 5px; \r\n");
      out.write("  margin:20px;\r\n");
      out.write("  font-size:16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar a:hover {\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("  background-color: #555;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write(".menu-bar .p{\r\n");
      out.write("color: #ffd400;\r\n");
      out.write("font-size: 15px;\r\n");
      out.write(" margin:20px;\r\n");
      out.write("}\r\n");
      out.write(".menu-bar .h3{\r\n");
      out.write("color: #ffd400;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sub-menu {\r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write(".menu-bar.active {\r\n");
      out.write("  left: 0;\r\n");
      out.write("}\r\n");
      out.write(".menu-icon {\r\n");
      out.write("  display: block;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  right: 10px;\r\n");
      out.write("  transform: translateY(-50%);\r\n");
      out.write("}\r\n");
      out.write(".menu-icon i {\r\n");
      out.write("  font-size: 36px;\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"menu-bar\">\r\n");
      out.write("<a href=\"index\" style=\"margin:0px 20px;\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/front/LOGOy.png\" style=\"width:140px; hight: auto;\" title=\"꿀팁홈페이지로가기\"></a>\r\n");
      out.write("<p class=\"p\"style=\"margin-bottom:40px;\">관리자님 반갑습니다</p>\r\n");
      out.write("<h3 class=\"h3\"><a style=\"font-size:18.72px; font-weight:bold;\" href=\"goChart\">메인으로가기</a></h3>\r\n");
      out.write("  <a href=\"listuser\">회원리스트</a>\r\n");
      out.write("  <a href=\"listlesson\">강의리스트</a>\r\n");
      out.write("  <a href=\"getReportList\">블랙리스트관리</a>\r\n");
      out.write("  <a href=\"getPotentialTiperList\">승급요청처리</a>\r\n");
      out.write("  <a href=\"adminNoticeList\">공지사항 관리</a>\r\n");
      out.write("  <a href=\"adminFaqList\">F A Q 관리</a>\r\n");
      out.write("  <a href=\"callEscrowList\">에스크로내역</a>\r\n");
      out.write("  <a href=\"getDisputeResolutionList\">강의 완료 및 취소</a>\r\n");
      out.write("  <a href=\"adminChkBtn\">관리자정보수정</a>\r\n");
      out.write("  <a class=\"p\" href=\"logOut\"style=\"font-weight:bold;font-size:18px;\">관리자 로그아웃</a>\r\n");
      out.write("<div class=\"menu-icon\">\r\n");
      out.write("    <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write(" const menuBar = document.querySelector('.menu-bar');\r\n");
      out.write(" const subMenus = document.querySelectorAll('.sub-menu');\r\n");
      out.write(" const menuIcon = document.querySelector('.menu-icon');\r\n");
      out.write("\r\n");
      out.write(" menuBar.addEventListener('mouseover', () => {\r\n");
      out.write("   menuBar.classList.add('active');\r\n");
      out.write("   subMenus.forEach(subMenu => subMenu.style.display = 'block');\r\n");
      out.write("   menuIcon.style.display = 'none';\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write(" menuBar.addEventListener('mouseout', () => {\r\n");
      out.write("   menuBar.classList.remove('active');\r\n");
      out.write("   subMenus.forEach(subMenu => subMenu.style.display = 'none');\r\n");
      out.write("   if (!menuBar.classList.contains('active')) {\r\n");
      out.write("     menuIcon.style.display = 'block';\r\n");
      out.write("   }\r\n");
      out.write(" });\r\n");
      out.write("</script> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h2 style=\"margin: 40px 0px;\">회원 리스트</h2>\r\n");
      out.write("		<button id=\"view-all-button\"\r\n");
      out.write("			onclick=\"viewAllFnc()\">전체목록보기</button>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<div id=\"search_wrapper\">\r\n");
      out.write("			<select class=\"search002\" id=\"user-condition\" name=\"user_condition\"\r\n");
      out.write("				style=\"display: inline-block !important; margin-right: 10px;\">\r\n");
      out.write("\r\n");
      out.write("				<option value=\"user_id\">회원아이디</option>\r\n");
      out.write("				<option value=\"user_name\">회원명</option>\r\n");
      out.write("			</select> <input class=\"search002\" type=\"text\" name=\"user_search\"\r\n");
      out.write("				id=\"user-search\" placeholder=\"검색어를 입력해주세요.\">\r\n");
      out.write("			<button class=\"btn btn-success\" type=\"button\"\r\n");
      out.write("				class=\"search002\"  onclick=\"btnSFnc()\"\r\n");
      out.write("				style=\"outline: none; border: none; background: transparent;\">\r\n");
      out.write("				<i class=\"fa fa-search\" style=\"font-size: 24px; color: #FFD400; cursor: pointer;\"></i>\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr class=\"hrFirst\">\r\n");
      out.write("		<br>\r\n");
      out.write("		<span id=\"displayCount\"></span>\r\n");
      out.write("		<table class=\"cont1_table\" style=\"table-layout: fixed;\">\r\n");
      out.write("			<thead class=\"btn-primary\">\r\n");
      out.write("				<tr class=\"pagination-row\">\r\n");
      out.write("					<th style=\"width: 14%\">아이디</th>\r\n");
      out.write("					<th style=\"width: 9%\">이름</th>\r\n");
      out.write("					<th style=\"width: 40%\">주소</th>\r\n");
      out.write("					<th style=\"width: 12%\">전화번호</th>\r\n");
      out.write("					<th style=\"width: 18%\">이메일</th>\r\n");
      out.write("					<th style=\"width: 11%\">관심TIP</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody id=\"dataTableBody\">\r\n");
      out.write("\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("		<ul id=\"pagingul\">\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
