/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-21 06:54:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.escrow;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ggul.zip.escrow.EscrowVO;
import java.util.*;
import java.util.Date;

public final class disputeResolution_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/escrow/../queen/adminNavbar.jsp", Long.valueOf(1684594758000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1683079470908L));
    _jspx_dependants.put("jar:file:/C:/swork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/honeytiper/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.ggul.zip.escrow.EscrowVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!-- <title>Insert title here</title> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("*{\r\n");
      out.write("	font-family: none;\r\n");
      out.write("}\r\n");
      out.write(".menu-bar {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  left: -190px;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  width: 230px;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  background-color: #333;\r\n");
      out.write("  overflow: auto;\r\n");
      out.write("  transition: left 0.3s ease-in-out; \r\n");
      out.write("}\r\n");
      out.write(".menu-bar a {\r\n");
      out.write("  display: block;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-decoration: none !important;\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  transition: 0.3s;\r\n");
      out.write("  padding: 5px; \r\n");
      out.write("  margin:20px;\r\n");
      out.write("  font-size:16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar a:hover {\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("  background-color: #555;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write(".menu-bar .p{\r\n");
      out.write("color: #ffd400;\r\n");
      out.write("font-size: 15px;\r\n");
      out.write(" margin:20px;\r\n");
      out.write("}\r\n");
      out.write(".menu-bar .h3{\r\n");
      out.write("color: #ffd400;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sub-menu {\r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write(".menu-bar.active {\r\n");
      out.write("  left: 0;\r\n");
      out.write("}\r\n");
      out.write(".menu-icon {\r\n");
      out.write("  display: block;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  right: 10px;\r\n");
      out.write("  transform: translateY(-50%);\r\n");
      out.write("}\r\n");
      out.write(".menu-icon i {\r\n");
      out.write("  font-size: 36px;\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"menu-bar\">\r\n");
      out.write("<a href=\"index\" style=\"margin:0px 20px;\"><img onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/front/default.png'\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/front/LOGOy.png\" style=\"width:140px; hight: auto;\" title=\"꿀팁홈페이지로가기\"></a>\r\n");
      out.write("<p class=\"p\"style=\"margin-bottom:40px;\">관리자님 반갑습니다</p>\r\n");
      out.write("<h3 class=\"h3\"><a style=\"font-size:18.72px; font-weight:bold;\" href=\"goChart\">메인으로가기</a></h3>\r\n");
      out.write("  <a href=\"listuser\">회원리스트</a>\r\n");
      out.write("  <a href=\"listlesson\">강의리스트</a>\r\n");
      out.write("  <a href=\"getReportList\">블랙리스트관리</a>\r\n");
      out.write("  <a href=\"getPotentialTiperList\">승급요청처리</a>\r\n");
      out.write("  <a href=\"adminNoticeList\">공지사항 관리</a>\r\n");
      out.write("  <a href=\"adminFaqList\">F A Q 관리</a>\r\n");
      out.write("  <a href=\"callEscrowList\">에스크로내역</a>\r\n");
      out.write("  <a href=\"getDisputeResolutionList\">강의완료 및 취소</a>\r\n");
      out.write("  <a href=\"adminChkBtn\">관리자정보수정</a>\r\n");
      out.write("  <a class=\"p\" href=\"logOut\"style=\"font-weight:bold;font-size:18px;\">관리자 로그아웃</a>\r\n");
      out.write("<div class=\"menu-icon\">\r\n");
      out.write("    <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write(" const menuBar = document.querySelector('.menu-bar');\r\n");
      out.write(" const subMenus = document.querySelectorAll('.sub-menu');\r\n");
      out.write(" const menuIcon = document.querySelector('.menu-icon');\r\n");
      out.write("\r\n");
      out.write(" menuBar.addEventListener('mouseover', () => {\r\n");
      out.write("   menuBar.classList.add('active');\r\n");
      out.write("   subMenus.forEach(subMenu => subMenu.style.display = 'block');\r\n");
      out.write("   menuIcon.style.display = 'none';\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write(" menuBar.addEventListener('mouseout', () => {\r\n");
      out.write("   menuBar.classList.remove('active');\r\n");
      out.write("   subMenus.forEach(subMenu => subMenu.style.display = 'none');\r\n");
      out.write("   if (!menuBar.classList.contains('active')) {\r\n");
      out.write("     menuIcon.style.display = 'block';\r\n");
      out.write("   }\r\n");
      out.write(" });\r\n");
      out.write("</script> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<title>꿀TIPer 관리자 - 강의완료 및 취소</title>\r\n");
      out.write("<!-- 퀸컨트롤러에있음 -->\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("  width: 65%;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("tr {\r\n");
      out.write("	height: 24px;\r\n");
      out.write("	padding: 18px 0px;\r\n");
      out.write("}\r\n");
      out.write(".cont1_table {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	border-spacing: 0px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cont1_th {\r\n");
      out.write("	background-color: #F0F0F0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thCenter1 {\r\n");
      out.write("   margin: 10px 5px;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   padding: 5px;\r\n");
      out.write("   border-bottom: 1px solid lightgray;\r\n");
      out.write("   font-size: 16px;;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdCenter1 {\r\n");
      out.write("   margin: 10px 5px;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   padding: 5px 0;\r\n");
      out.write("   border-bottom: 1px solid lightgray;\r\n");
      out.write("   font-size: 0.9rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".tdcenter1_btn1 {\r\n");
      out.write("	border-style: none;\r\n");
      out.write("	background: #FFD400;\r\n");
      out.write("	color: #5c3b0c;\r\n");
      out.write("	margin: 5px;\r\n");
      out.write("	padding: 5px 18px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tdcenter1_btn2 {\r\n");
      out.write("	border-style: none;\r\n");
      out.write("	background: #E9E9E9;\r\n");
      out.write("	color: #5c3b0c;\r\n");
      out.write("	margin: 5px;\r\n");
      out.write("	padding: 5px 18px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#view-all-button {\r\n");
      out.write("  border-style: none;\r\n");
      out.write("    background: #FFD400;\r\n");
      out.write("    color: #5c3b0c;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    padding: 5px 18px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 12pt;\r\n");
      out.write("    font-weight: bolder;\r\n");
      out.write("}\r\n");
      out.write(".btn-success {\r\n");
      out.write("	border-style: none;\r\n");
      out.write("    background: #FFD400;\r\n");
      out.write("    color: #5c3b0c;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 12pt;\r\n");
      out.write("    font-weight: bolder;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#view-all-button:hover, .btn-success:hover {\r\n");
      out.write("  background-color: #E6B800;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pagingul {\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pagingul li {\r\n");
      out.write("  margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pagingul li a {\r\n");
      out.write("  display: block;\r\n");
      out.write("  padding: 5px 10px;\r\n");
      out.write("  border: 1px solid #ddd;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  color: #333;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pagingul li.on a {\r\n");
      out.write("  background-color: #FFD400;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write(" input[type=text]{\r\n");
      out.write("   width: 170px;\r\n");
      out.write("   height: 25px;\r\n");
      out.write("  }\r\n");
      out.write("  select{\r\n");
      out.write("    width: 110px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<h2 style=\"margin:40px 0px;\">강의완료 및 취소</h2>\r\n");
      out.write("\r\n");
      out.write("  <div id=\"top_bar\">\r\n");
      out.write("				<div id=\"search_wrapper\">\r\n");
      out.write("				<button id=\"view-all-button\" onclick=\"viewAll()\">전체목록보기</button><br>\r\n");
      out.write("					<select class=\"search\" id=\"sel1\" name=\"search_condition\"\r\n");
      out.write("						style=\"display: inline-block !important;\">\r\n");
      out.write("						<option value=\"escrow_user_id\">회원아이디</option>\r\n");
      out.write("						<option value=\"tiper_user_id\">강사아이디</option>\r\n");
      out.write("					</select> <input class=\"search\" type=\"text\" name=\"search_keyword\" id=\"sel2\"\r\n");
      out.write("						placeholder=\"검색어를 입력하세요.\">\r\n");
      out.write("					<button class=\"btn btn-success\" type=\"submit\" class=\"search\" id=\"sel3\"style=\"outline:none; border:none; background:transparent;\">\r\n");
      out.write("					<i class=\"fa fa-search\" style=\"font-size:24px; color:#FFD400; pading:0px\"></i></button>\r\n");
      out.write("						<br><br>\r\n");
      out.write("						 <label for=\"status-0\">신청중</label>\r\n");
      out.write("						<input type=\"radio\" id=\"status-0\" name=\"escrow_status\" value=\"0\">\r\n");
      out.write("						<label for=\"status-1\">진행중</label>\r\n");
      out.write("						<input type=\"radio\" id=\"status-1\" name=\"escrow_status\" value=\"1\">\r\n");
      out.write("<!-- 						<label for=\"status-12\">전체</label> -->\r\n");
      out.write("<!-- 						<input type=\"radio\" id=\"status-12\" name=\"escrow_status\" value=\"12\"> -->\r\n");
      out.write("						 <hr class=\"hrFirst\">\r\n");
      out.write("						 <br>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("            <span id=\"displayCount\"></span>\r\n");
      out.write("            <table class=\"cont1_table\">\r\n");
      out.write("	            <thead>\r\n");
      out.write("	                <tr class=\"cont1_th\" >\r\n");
      out.write("	                     <th class=\"thCenter1\" style=\"width:15%;\">강의시작날짜</th> \r\n");
      out.write("                       <th class=\"thCenter1\" style=\"width:10%;\">수강회원</th> \r\n");
      out.write("                       <th class=\"thCenter1\" style=\"width:25%;\">강의명</th>\r\n");
      out.write("                        <th class=\"thCenter1\" style=\"width:10%;\">강사회원</th>\r\n");
      out.write("                        <th class=\"thCenter1\" style=\"width:10%;\">금액</th>\r\n");
      out.write("                       <th class=\"thCenter1\" style=\"width:10%;\">진행상황</th>\r\n");
      out.write("                       <th class=\"thCenter1\" style=\"width:20%\">완료 or 취소</th>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	            </thead>\r\n");
      out.write("	            <tbody id=\"data_table_body\"></tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("	<ul id=\"pagingul\"></ul>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("var totalData; //총 데이터 수\r\n");
      out.write("var dataPerPage=10; //한 페이지에 나타낼 글 수\r\n");
      out.write("var pageCount = 5; //한 번에 나타낼 페이지 수 ([이전] 1 2 3 4 5 [다음])\r\n");
      out.write("var globalCurrentPage= 1; //현재 페이지\r\n");
      out.write("var dataList; //데이터 리스트\r\n");
      out.write("\r\n");
      out.write("//날짜형식맞춰야해서 넣은것\r\n");
      out.write("function formatDate(date) {\r\n");
      out.write("	  var year = date.getFullYear();\r\n");
      out.write("	  var month = date.getMonth() + 1;\r\n");
      out.write("	  var day = date.getDate();\r\n");
      out.write("	  var formattedDate = year + '-' + month + '-' + day;\r\n");
      out.write("	  return formattedDate;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write(" \r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("	\r\n");
      out.write("     //totalData(총 데이터 수) 구하기 항상실행이여서 컨트롤러에서 걍가져옴아약스X\r\n");
      out.write("	 dataList = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${DisputeListtJSON}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";		\r\n");
      out.write("     \r\n");
      out.write("     //totalData(총 데이터 수) 구하기\r\n");
      out.write("	 totalData = dataList.length;\r\n");
      out.write("     \r\n");
      out.write("	 //글 목록 표시 호출 (테이블 생성)\r\n");
      out.write("     displayData(1, dataPerPage);\r\n");
      out.write("	 \r\n");
      out.write("   //페이징 표시 호출\r\n");
      out.write("     paging(totalData, dataPerPage, pageCount, 1);\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("//현재 페이지(currentPage)와 페이지당 글 개수(dataPerPage) 반영\r\n");
      out.write("function displayData(currentPage, dataPerPage) {\r\n");
      out.write("\r\n");
      out.write("  let chartHtml = \"\";\r\n");
      out.write("\r\n");
      out.write("//Number로 변환하지 않으면 아래에서 +를 할 경우 스트링 결합이 되어버림.. \r\n");
      out.write("  currentPage = Number(currentPage);\r\n");
      out.write("  dataPerPage = Number(dataPerPage);\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" if (totalData < (currentPage - 1) * dataPerPage + dataPerPage){\r\n");
      out.write("	\r\n");
      out.write("	  for (\r\n");
      out.write("		var i = (currentPage - 1) * dataPerPage;\r\n");
      out.write("		    i < totalData;\r\n");
      out.write("			     i++\r\n");
      out.write("			   ) {\r\n");
      out.write("		  chartHtml +=\r\n");
      out.write("		 	  '<tr><td class=\"tdCenter1\">' + (dataList[i].escrow_start ? formatDate(new Date(dataList[i].escrow_start)) : \"\") + \r\n");
      out.write("		 	  '</td><td class=\"tdCenter1\">' +(dataList[i].escrow_user_id || \"\")  +\r\n");
      out.write("		 	  '</td><td class=\"tdCenter1\">' +(dataList[i].lesson_title || \"\")  +\r\n");
      out.write("		 	  '</td><td class=\"tdCenter1\">' +(dataList[i].tiper_user_id || \"\") +\r\n");
      out.write("		 	  '</td><td class=\"tdCenter1\">' +(dataList[i].escrow_price || \"\").toLocaleString()+\r\n");
      out.write("		 	  '</td><td class=\"tdCenter1\">' +(dataList[i].escrow_status === 0 ? \"신청중\" :\r\n");
      out.write("									dataList[i].escrow_status === 1 ? \"진행중\" : \"\" )+\r\n");
      out.write("		 	  '</td><td class=\"tdCenter1\">' +\r\n");
      out.write("		 	 '<button type=\"button\" class=\"tdcenter1_btn1\" title=\"강사에게 강의료가 입금됩니다\" onclick=\"location.href=\\'/forcedCompletion?escrow_num='+dataList[i].escrow_num+'&escrow_user_id='+dataList[i].escrow_user_id+'&tiper_user_id='+dataList[i].tiper_user_id+'&escrow_price='+dataList[i].escrow_price+'&lesson_title='+dataList[i].lesson_title+'\\'\">완료</button>'+\r\n");
      out.write("		 	 '<button type=\"button\" class=\"tdcenter1_btn2\" title=\"회원에게 환불처리됩니다\" onclick=\"location.href=\\'/cancel?escrow_num='+dataList[i].escrow_num+'&escrow_user_id='+dataList[i].escrow_user_id+'&tiper_user_id='+dataList[i].tiper_user_id+'&escrow_price='+dataList[i].escrow_price+'&lesson_title='+dataList[i].lesson_title+'\\'\">취소</button></tr>';\r\n");
      out.write("			   } \r\n");
      out.write(" }else{ \r\n");
      out.write("  \r\n");
      out.write("  for (\r\n");
      out.write("    var i = (currentPage - 1) * dataPerPage;\r\n");
      out.write("    i < (currentPage - 1) * dataPerPage + dataPerPage;\r\n");
      out.write("    i++\r\n");
      out.write("  ) {\r\n");
      out.write("	  chartHtml +=\r\n");
      out.write("		  '<tr><td class=\"tdCenter1\">' + (dataList[i].escrow_start ? formatDate(new Date(dataList[i].escrow_start)) : \"\") + \r\n");
      out.write("	 	  '</td><td class=\"tdCenter1\">' +(dataList[i].escrow_user_id || \"\")  +\r\n");
      out.write("	 	  '</td><td class=\"tdCenter1\">' +(dataList[i].lesson_title || \"\")  +\r\n");
      out.write("	 	  '</td><td class=\"tdCenter1\">' +(dataList[i].tiper_user_id || \"\") +\r\n");
      out.write("	 	 '</td><td class=\"tdCenter1\">' +(dataList[i].escrow_price || \"\").toLocaleString()+\r\n");
      out.write("	 	  '</td><td class=\"tdCenter1\">' +(dataList[i].escrow_status === 0 ? \"신청중\" :\r\n");
      out.write("	 							dataList[i].escrow_status === 1 ? \"진행중\" : \"\" )+\r\n");
      out.write("	 	  '</td><td class=\"tdCenter1\">' +\r\n");
      out.write("	 	  '<button type=\"button\" class=\"tdcenter1_btn1\" title=\"강사에게 강의료가 입금됩니다\" onclick=\"location.href=\\'/forcedCompletion?escrow_num='+dataList[i].escrow_num+'&escrow_user_id='+dataList[i].escrow_user_id+'&tiper_user_id='+dataList[i].tiper_user_id+'&escrow_price='+dataList[i].escrow_price+'&lesson_title='+dataList[i].lesson_title+'\\'\">완료</button>'+\r\n");
      out.write("	 	  '<button type=\"button\" class=\"tdcenter1_btn2\" title=\"회원에게 환불처리됩니다\" onclick=\"location.href=\\'/cancel?escrow_num='+dataList[i].escrow_num+'&escrow_user_id='+dataList[i].escrow_user_id+'&tiper_user_id='+dataList[i].tiper_user_id+'&escrow_price='+dataList[i].escrow_price+'&lesson_title='+dataList[i].lesson_title+'\\'\">취소</button></tr>';\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(" if( typeof chartHtml == \"undefined\" || chartHtml == ''){ chartHtml +=\"<tr><td colspan='7' style='text-align:center;' id='if_undefined'>해당정보가 없습니다.</td></tr>\"}\r\n");
      out.write("\r\n");
      out.write("$(\"#data_table_body\").html(chartHtml);\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("function paging(totalData, dataPerPage, pageCount, currentPage) {\r\n");
      out.write("\r\n");
      out.write("	  totalPage = Math.ceil(totalData / dataPerPage); //총 페이지 수\r\n");
      out.write("	  \r\n");
      out.write("	  if(totalPage<pageCount){\r\n");
      out.write("	    pageCount=totalPage;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  let pageGroup = Math.ceil(currentPage / pageCount); // 페이지 그룹\r\n");
      out.write("	  let endPage = pageGroup * pageCount; //화면에 보여질 마지막 페이지 번호\r\n");
      out.write("	  \r\n");
      out.write("	  if (endPage > totalPage) {\r\n");
      out.write("	    endPage = totalPage;\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("	  let startPage = endPage - (pageCount - 1); //화면에 보여질 첫번째 페이지 번호\r\n");
      out.write("	  let next = Number(currentPage)+1;\r\n");
      out.write("	  let prev = Number(currentPage)-1;\r\n");
      out.write("\r\n");
      out.write("	  let pageHtml = \"\";\r\n");
      out.write("\r\n");
      out.write("	  if (prev > 0) {\r\n");
      out.write("	    pageHtml += \"<li><a href='javascript:void(0)' id='prev'> 이전 </a></li>\";\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("	 //페이징 번호 표시 \r\n");
      out.write("	  for (var i = startPage; i <= endPage; i++) {\r\n");
      out.write("	    if (currentPage == i) {\r\n");
      out.write("	      pageHtml +=\r\n");
      out.write("	        '<li class=\"on\"><a href=\"javascript:void(0)\" id=\"' + i + '\">' + i + '</a></li>';\r\n");
      out.write("	    } else {\r\n");
      out.write("	      pageHtml += \"<li><a href='javascript:void(0)' id='\" + i + \"'>\" + i + \"</a></li>\";\r\n");
      out.write("	    }\r\n");
      out.write("	  }\r\n");
      out.write("	 \r\n");
      out.write("	 \r\n");
      out.write("	  if (next <= totalPage) {\r\n");
      out.write("	    pageHtml += '<li><a href=\"javascript:void(0);\" id=\"next\"> 다음 </a></li>';\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("	  $(\"#pagingul\").html(pageHtml);\r\n");
      out.write("	  let displayCount = \"\";\r\n");
      out.write("	  displayCount = \"현재 1 - \" + totalPage + \" 페이지 / \" + totalData + \"건\";\r\n");
      out.write("	  $(\"#displayCount\").text(displayCount);\r\n");
      out.write("	  \r\n");
      out.write("	  //페이징 번호 클릭 이벤트 \r\n");
      out.write("	  $(\"#pagingul li a\").click(function () {\r\n");
      out.write("	    let $id = $(this).attr(\"id\");\r\n");
      out.write("	    selectedPage = $(this).text();\r\n");
      out.write("\r\n");
      out.write("	    if ($id == \"next\") selectedPage = next;\r\n");
      out.write("	    if ($id == \"prev\") selectedPage = prev;\r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("	    //전역변수에 선택한 페이지 번호를 담는다...\r\n");
      out.write("	    globalCurrentPage = selectedPage;\r\n");
      out.write("	 \r\n");
      out.write("	    console.log(\"클릭시 글로벌 \"+globalCurrentPage);\r\n");
      out.write("	    \r\n");
      out.write("	    //글 목록 표시 재호출\r\n");
      out.write("	    displayData(globalCurrentPage, dataPerPage);\r\n");
      out.write("	    //페이징 표시 재호출\r\n");
      out.write("	    paging(totalData, dataPerPage, pageCount, globalCurrentPage);\r\n");
      out.write("	  });\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("$('input[name=\"escrow_status\"]').on('click', function () {\r\n");
      out.write("    var escrow_status = $('input[name=\"escrow_status\"]:checked').val();\r\n");
      out.write("    var search_condition=$('#sel1').val() || null;\r\n");
      out.write("	var search_keyword=$('#sel2').val() || null;\r\n");
      out.write("    searchAndStatus(escrow_status, search_condition, search_keyword);\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("function searchAndStatus(escrow_status, search_condition, search_keyword) {\r\n");
      out.write("	globalCurrentPage = 1;\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		method: \"POST\",\r\n");
      out.write("		url: 'searchAndStatus',\r\n");
      out.write("		data: {\r\n");
      out.write("			escrow_status: escrow_status,\r\n");
      out.write("			search_condition: search_condition,\r\n");
      out.write("			search_keyword: search_keyword\r\n");
      out.write("		},\r\n");
      out.write("		success: function (data) {\r\n");
      out.write("			console.log(\"Selected Data:\", {\r\n");
      out.write("				escrow_status: escrow_status,\r\n");
      out.write("				search_condition: search_condition,\r\n");
      out.write("				search_keyword: search_keyword\r\n");
      out.write("			});\r\n");
      out.write("			totalData = data.length;\r\n");
      out.write("			dataList = data;\r\n");
      out.write("\r\n");
      out.write("			//글 목록 표시 재호출\r\n");
      out.write("			displayData(globalCurrentPage, dataPerPage);\r\n");
      out.write("			//페이징 표시 재호출\r\n");
      out.write("			paging(totalData, dataPerPage, pageCount, globalCurrentPage);\r\n");
      out.write("		}\r\n");
      out.write("	}); // success 함수의 닫는 괄호 이동\r\n");
      out.write("}\r\n");
      out.write("function viewAll() {\r\n");
      out.write("	 location.reload();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(\"#sel3\").click(function(){\r\n");
      out.write("	console.log(\"여기오니\");\r\n");
      out.write("	var search_condition=$('#sel1').val();\r\n");
      out.write("	var search_keyword=$('#sel2').val();\r\n");
      out.write("    fetchData(search_condition, search_keyword);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function fetchData(search_condition, search_keyword) {\r\n");
      out.write("	$.ajax({ // ajax로 데이터 가져오기\r\n");
      out.write("		method: \"POST\",\r\n");
      out.write("		url: \"searchDispute\",\r\n");
      out.write("	 	data: {search_condition:search_condition, search_keyword:search_keyword},\r\n");
      out.write("		dataType: \"json\",\r\n");
      out.write("		async:false,\r\n");
      out.write("		success: function (data) {\r\n");
      out.write("		   //totalData(총 데이터 수) 구하기\r\n");
      out.write("		   totalData = data.length;\r\n");
      out.write("	       //데이터 대입\r\n");
      out.write("	       dataList=data;\r\n");
      out.write("		\r\n");
      out.write("	 //글 목록 표시 재호출\r\n");
      out.write("	 displayData(globalCurrentPage, dataPerPage);\r\n");
      out.write("	 //페이징 표시 재호출\r\n");
      out.write("	 paging(totalData, dataPerPage, pageCount, globalCurrentPage);\r\n");
      out.write("		}\r\n");
      out.write("	 });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/escrow/disputeResolution.jsp(138,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   <script type=\"text/javascript\">\r\n");
          out.write("       var message = \"");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\";\r\n");
          out.write("       alert(message);\r\n");
          out.write("   </script>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/escrow/disputeResolution.jsp(140,22) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
